package invariants

import "regexp"

// The two vocabularies this package scans tracked text for.
//
// EVERY PATTERN HERE IS WRITTEN SO THAT ITS OWN SOURCE TEXT DOES NOT MATCH IT.
// That is not a stylistic preference. This file is tracked text, so the leg
// defined here reads it like any other file, and a pattern spelled as a plain
// literal would refuse the file that defines it. The trick is that each pattern
// opens with a character class rather than with a bare character: the bytes
// `[Cc]laude` are not matched by the expression `[Cc]laude`, because the first
// byte of the source is `[` and the class does not hold it.
//
// TestTheVocabularyDoesNotRefuseItself is what holds that property, so a later
// pattern written as a plain literal reddens the suite instead of reddening the
// tree. Without it the repair somebody would reach for is an exclusion for this
// file, and a scanner that skips the file holding its own vocabulary is a
// scanner with a hole nobody can see from outside.

// credentialShapes holds the credential formats that have actually leaked in
// projects of this kind. It is a FLOOR AND NOT A GUARANTEE, which is worth
// stating here rather than only in the issue that asked for it: a credential
// scan trusted beyond its reach is worse than none, because it converts "we
// looked for these eight shapes" into "there are no secrets here".
//
// What it will not catch: a shape nobody has written yet, a credential a
// provider issues in a format not below, anything base64-wrapped or split
// across lines, and a password, which has no shape at all. Nothing here reads
// entropy, so a long random string that is a real key and matches none of these
// passes.
//
// Each entry names the issuer it belongs to, because a reader hitting a refusal
// needs to know what to rotate and not only that something matched.
var credentialShapes = []shape{
	{
		name:    "an AWS access key id",
		pattern: regexp.MustCompile(`AKIA[0-9A-Z]{16}`),
	},
	{
		name:    "a GitHub token",
		pattern: regexp.MustCompile(`gh[pousr]_[A-Za-z0-9]{36}`),
	},
	{
		name:    "a GitHub fine-grained personal access token",
		pattern: regexp.MustCompile(`github_pat_[A-Za-z0-9_]{22,}`),
	},
	{
		name:    "a private key block",
		pattern: regexp.MustCompile(`[-]{5}BEGIN [A-Z ]*PRIVATE KEY[-]{5}`),
	},
	{
		name:    "a Slack token",
		pattern: regexp.MustCompile(`xox[baprs][-][A-Za-z0-9-]{10,}`),
	},
	{
		name:    "a Google API key",
		pattern: regexp.MustCompile(`AIza[0-9A-Za-z_-]{35}`),
	},
	{
		name:    "a JSON web token",
		pattern: regexp.MustCompile(`eyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}`),
	},
}

// attributionMarkers holds the tool names and attribution lines that may not
// appear in tracked text. Where the origin of a passage genuinely matters it is
// stated in the passage rather than hidden, so this is not a rule against
// saying where something came from. It is a rule against a marker nobody chose
// to write arriving with a paste and staying.
//
// It holds the vocabulary rather than judging prose, which is the whole of what
// it can do. A passage written by a tool and carrying none of these strings
// reads exactly like one somebody typed, and nothing here separates them.
//
// The entries are narrow on purpose. An earlier draft of this leg matched the
// words "generated by", which the release milestone uses correctly about a bill
// of materials generated by the build, and a check that reddens honest prose is
// a check somebody switches off.
var attributionMarkers = []shape{
	{
		name:    "a tool name",
		pattern: regexp.MustCompile(`[Cc]laude [Cc]ode`),
	},
	{
		name:    "a tool name",
		pattern: regexp.MustCompile(`[Cc]hat[Gg][Pp][Tt]`),
	},
	{
		name:    "a tool name",
		pattern: regexp.MustCompile(`[Gg]it[Hh]ub [Cc]opilot`),
	},
	{
		name:    "an attribution trailer",
		pattern: regexp.MustCompile(`[Cc]o-[Aa]uthored-[Bb]y:`),
	},
	{
		name:    "a generated-by marker",
		pattern: regexp.MustCompile(`[Gg]enerated by an? (AI|LLM|language model)`),
	},
	{
		name:    "an assistant preamble",
		pattern: regexp.MustCompile(`[Aa]s an AI (language model|assistant)`),
	},
}

// shape is one entry in a vocabulary: what it is called in a refusal, and the
// expression that finds it.
type shape struct {
	name    string
	pattern *regexp.Regexp
}
